/**
 * This file defines the structure for the database tables.
 * This should be autogenerated by Kysely based on your database schema.
 * But with the time crunch this is a faster solution.
 */

import {
  ColumnType,
  Generated,
  Insertable,
  JSONColumnType,
  Selectable,
  Updateable,
} from "kysely";

export interface Database {
  person: PaymentsTable;
}

export interface PaymentsTable {
  id: Generated<number>;
  first_name: string;
  gender: "man" | "woman" | "other";
  last_name: string | null;
  created_at: ColumnType<Date, string | undefined, never>;
}
