/**
 * This file defines the structure for the database tables.
 * This should be autogenerated by Kysely based on your database schema.
 * But with the time crunch this is a faster solution.
 */

import { Generated, Selectable } from "kysely";

export interface Database {
  payments: PaymentsTable;
}

export interface PaymentsTable {
  ID: Generated<number>;
  Total: number;
  Record_type: "invoice" | "bill" | "none";
  Status: "pending" | "void" | "completed";
  Create_date: string;
  Modified_date: string;
}

export type SelectablePaymentsTable = Selectable<PaymentsTable>;
