/**
 * This file defines the structure for the database tables.
 * This should be autogenerated by Kysely based on your database schema.
 * But with the time crunch this is a faster solution.
 */

import { Generated } from "kysely";

export interface Database {
  person: PaymentsTable;
}

export interface PaymentsTable {
  id: Generated<number>;
  total: number;
  record_type: "invoice" | "bill" | "none";
  status: "pending" | "void" | "completed";
  create_date: string;
  modified_date: string;
}
